spring:
  datasource:
    initialization-mode: ALWAYS
    password: 123456
    schema: classpath:sql/schema.sql
    url: jdbc:h2:mem:dictdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true